#!/bin/bash

echo Generating new random routes...
singularity exec -B $TMPDIR:$TMPDIR webots_sumo.sif /usr/local/webots/projects/default/resources/sumo/bin/duarouter --route-files ../Simulations/HighwayMerge/worlds/LinkonMKZmyMap_net/sumo.flow.xml --net-file /home/mwfranc/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap_net/sumo.rou.xml --randomize-flows true --seed $RANDOM


echo Starting Webots on 'hostname'
singularity exec -B $TMPDIR:$TMPDIR webots_sumo.sif xvfb-run -a webots --stdout --stderr --batch --mode=realtime ~/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap.wbt

chmod +x ~/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap.wbt
awk '$0 ~ /port/ { $1 = "  " $1; $2++ } 1' ~/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap.wbt > tmp$$ && mv tmp$$ ~/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap.wbt

