#!/bin/bash

echo Generating new random routes...
singularity exec -B $TMPDIR:$TMPDIR webots_sumo.sif /usr/local/webots/projects/default/resources/sumo/bin/duarouter --route-files /home/mwfranc/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap_$(($PBS_ARRAY_INDEX % 8))_net/sumo.flow.xml --net-file /home/mwfranc/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap_$(($PBS_ARRAY_INDEX % 8))_net/sumo.net.xml --output-file /home/mwfranc/Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap_$(($PBS_ARRAY_INDEX % 8))_net/sumo.rou.xml --randomize-flows true --seed $RANDOM


echo Starting Webots on 'hostname'
singularity exec -B $TMPDIR:$TMPDIR webots_sumo.sif xvfb-run -a webots --stdout --stderr --batch --mode=realtime Webots.HPC/Simulations/HighwayMerge/worlds/LinkonMKZmyMap_$(($PBS_ARRAY_INDEX % 8)).wbt
